# Generated by Django 3.2.12 on 2023-08-26 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id'], 'verbose_name': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='default',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=django_countries.fields.CountryField(help_text='The country of the currency.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the currency was created.', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information about the currency.', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, help_text='The exchange rate of the currency.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Indicates if the currency is active or not.', max_length=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the currency was last updated.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Enter the first line of the address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Enter the second line of the address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the city', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Select the country', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Enter the postal or zip code', max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Invalid postal code', regex='^\\d{5}(?:[-\\s]\\d{4})?$')], verbose_name='Post/Zip-code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='The currency code.', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='The name of the currency.', max_length=50),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.state', verbose_name='State/Province'),
        ),
    ]
