# Generated by Django 3.2.12 on 2023-08-26 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20230826_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(blank=True, default='', help_text='Enter the first line of the address', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Enter the city', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default=0, help_text='Enter the postal or zip code', max_length=64, validators=[django.core.validators.RegexValidator(message='Invalid postal code', regex='^\\d{5}(?:[-\\s]\\d{4})?$')], verbose_name='Post/Zip-code'),
            preserve_default=False,
        ),
    ]
