# Generated by Django 3.1.13 on 2021-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_tenantuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
