# Generated by Django 3.1.13 on 2021-07-29 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('suburb', models.CharField(blank=True, max_length=55, null=True, verbose_name='Suburb')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('postcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code')),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^(\\+27|0)[6-8][0-9]{8}$')])),
                ('job_description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('marketing', 'Marketing'), ('finance', 'Finance'), ('management', 'Management'), ('accounts', 'Accounts'), ('technical', 'Technical'), ('sales', 'Sales')], max_length=250, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('educational_qualification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('suburb', models.CharField(blank=True, max_length=55, null=True, verbose_name='Suburb')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('postcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code')),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^(\\+27|0)[6-8][0-9]{8}$')])),
                ('organisation', models.TextField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_description', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('suburb', models.CharField(blank=True, max_length=55, null=True, verbose_name='Suburb')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('postcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code')),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^(\\+27|0)[6-8][0-9]{8}$')])),
                ('educational_qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True, verbose_name=(('marketing', 'Marketing'), ('finance', 'Finance'), ('management', 'Management'), ('accounts', 'Accounts'), ('technical', 'Technical'), ('sales', 'Sales')))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
