# Generated by Django 3.1.13 on 2021-08-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210808_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='country',
        ),
    ]
