# Generated by Django 3.1.13 on 2021-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_staff_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='country',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
