# Generated by Django 3.1.13 on 2021-08-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='province',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='suburb',
        ),
    ]
