# Generated by Django 3.1.13 on 2021-08-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210811_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
