# Generated by Django 3.1.13 on 2021-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210813_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, default='dist/img/logo.png', null=True, upload_to='images/logo'),
        ),
    ]
