# Generated by Django 3.1.13 on 2021-08-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210813_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='images/logo'),
        ),
    ]
