# Generated by Django 3.1.13 on 2021-08-13 13:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210813_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
