# Generated by Django 3.1.13 on 2021-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210813_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to=''),
        ),
    ]
