# Generated by Django 3.1.13 on 2021-08-14 20:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210813_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(blank=True, default='info@company.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/logo'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='name',
            field=models.CharField(blank=True, default='Organisation Name', max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+27829999999', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='website',
            field=models.URLField(blank=True, default='http://exmple.com', null=True),
        ),
    ]
