# Generated by Django 3.1.13 on 2021-08-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210814_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
