# Generated by Django 3.1.13 on 2021-08-19 09:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210815_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.FileField(blank=True, default='static/core/logo.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to='images'),
        ),
    ]
