# Generated by Django 3.2.12 on 2023-08-26 07:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230204_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Coupon code', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='End date of coupon validity'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the coupon is currently active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, help_text='Minimum order amount required to use the coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redeem_by',
            field=models.DateField(default=datetime.date.today, help_text='Date by which the coupon must be redeemed'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Start date of coupon validity'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the coupon has been used', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(help_text='Maximum number of times coupon can be used', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
