# Generated by Django 4.2 on 2024-04-29 09:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20230826_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of coupon validity', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redeem_by',
            field=models.DateField(default=datetime.datetime(2024, 5, 29, 9, 54, 7, 555509, tzinfo=datetime.timezone.utc), help_text='Date by which the coupon must be redeemed'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of coupon validity'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, help_text='Number of times the coupon has been used', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
