# Generated by Django 3.2.12 on 2022-12-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_manager', '0007_auto_20220407_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('groups_manager.group',),
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('groups_manager.group',),
        ),
    ]
