version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
      - image: postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: test_project
        ports:
          - "5432:5432"

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install coverage
            pip install -r requirements.txt
      - run:
          name: Create Groups table
          command: |
            cp -r multitenancy/test/* .
            python manage.py makemigrations
            python manage.py migrate
      - run:
          name: Run tests
          command: coverage run manage.py test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - build:
          filters:
            branches:
              only:
                - main
            tags:
              ignore: /.*/
