# Generated by Django 3.2.12 on 2023-08-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_refund_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateways'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='default',
            field=models.BooleanField(default=False, help_text='Whether this payment gateway is the default gateway.'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='description',
            field=models.TextField(help_text='A description of the payment gateway.'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(help_text='The name of the payment gateway.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], help_text='The status of the payment gateway.', max_length=10),
        ),
    ]
