# Generated by Django 3.2.12 on 2023-08-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20230826_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(help_text='The currency used for the payment.', on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
    ]
