# Generated by Django 3.2.12 on 2023-08-26 11:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=django_countries.fields.CountryField(help_text='The country of the currency.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the currency was created.', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information about the currency.', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.BooleanField(default=True, help_text='Indicates if the currency is active or not.'),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the currency was last updated.'),
        ),
        migrations.CreateModel(
            name='CurrencyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('USD', 'US Dollar')], default=None, editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.currency')),
            ],
        ),
    ]
