# Generated by Django 3.2.12 on 2023-08-26 11:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20230826_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=django_countries.fields.CountryField(help_text='The country of the currency.', max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the currency was created.'),
        ),
    ]
