# Generated by Django 3.2.12 on 2023-08-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20230826_2325'),
        ('billing', '0008_auto_20230826_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyamount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(help_text='The currency used for the payment.', on_delete=django.db.models.deletion.PROTECT, to='settings.currency'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
