# Generated by Django 3.2.12 on 2023-01-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20230126_1655'),
        ('apps', '0013_alter_tenant_trail_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subscription',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='subscriptions.subscription'),
        ),
    ]
