# Generated by Django 3.2.12 on 2023-08-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_tenant_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('personal', 'personal'), ('freemium', 'freemium'), ('premium', 'premium'), ('business', 'business')], default='personal', max_length=200),
        ),
    ]
