# Generated by Django 3.2.12 on 2023-08-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_plan_name'),
        ('apps', '0015_alter_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('personal', 'personal'), ('freemium', 'freemium'), ('premium', 'premium'), ('business', 'business')], default='default', max_length=200),
        ),
    ]
