# Generated by Django 3.2.18 on 2024-04-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20240418_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
