# Generated by Django 3.2.18 on 2024-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(choices=[('tenant', 'Tenant App'), ('domain', 'Custom Domain'), ('third_party', '3rd party App')], default='tenant', max_length=115, unique=True),
        ),
    ]
