# Generated by Django 3.2.18 on 2024-04-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_alter_producttype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('-pk',)},
        ),
    ]
