# Generated by Django 3.2.12 on 2022-10-02 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Tenant',
        ),
    ]
