name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_URL: postgres://postgres@localhost/test

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: testing_project
        ports: [5432]


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        cp -r multitenancy/test/* .
        python -m venv venv
        source venv/bin/activate
        pip install coverage
        pip install -r requirements.txt

    - name: Run tests
      run: |
        coverage run manage.py test



