name: Django Multitenancy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

        services:
          postgres:
            image: postgres:12
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: testing
              POSTGRES_DB: test_project
            ports:
              - 5432:5432
            # needed because the postgres container does not provide a healthcheck
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Create Groups table
      run: | 
        cp -r multitenancy/test/* .
        python manage.py makemigrations
        
    - name: Run tests
      run: coverage run manage.py test
